name: Containerized application CI workflow

on:
  push:
    branches:
      - master
      - main
      - release
      - develop
  pull_request:
    branches:
      - master
      - main
      - release
      - develop
  workflow_dispatch: # Allows manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Grant write permission for packages (GHCR)

    steps:
      - name: Get Short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short_sha_action
        with:
          length: 7    # Optional: specify desired length

      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Use the secret you created

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}  # Image name format for GHCR

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          APP_IMAGE: ghcr.io/${{ github.repository }}:test
            # old tag: ${{ steps.short_sha_action.outputs.sha }}
        with:
          context: ./my-app/ # Path to your Dockerfile and build context
          push: true
          tags: |
            ${{ env.APP_IMAGE }}
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploying.. Decodificar chave privada
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OCI_WEB1_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Adicionar chave ao agente SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # - name: 'Make site code package'
      #   run: |
      #     cd ./my-app
      #     zip -r ~/code.zip . -x .git/** .github/** .git*
      - name: 'Deploy container to server'
        env:
          APP_IMAGE: ghcr.io/${{ github.repository }}:${{ steps.short_sha_action.outputs.sha }}
        run: |
          scp -o StrictHostKeyChecking=no -v -i ~/.ssh/id_rsa -P 22 ./my-app/deploy_run_docker.sh \
            opc@${{ vars.OCI_WEB1_PUB_IP }}:${{ vars.APPSRV_DIR }}    # use "scp ... -r <directory> to recursive copy
          # ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no opc@${{ vars.OCI_WEB1_PUB_IP }} \
          #   "unzip -o ${{ vars.APPSRV_DIR }}/code.zip -d ${{ vars.APPSRV_DIR }}"
          # ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no opc@${{ vars.OCI_WEB1_PUB_IP }} \
          #   "rm -rf ${{ vars.APPSRV_DIR }}/*.zip"
         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no opc@${{ vars.OCI_WEB1_PUB_IP }} \
            "cd ${{ vars.APPSRV_DIR }}; chmod +x ./deploy_run_docker.sh; sudo ./deploy_run_docker.sh ${{ secrets.GHCR_TOKEN }} ${{ env.APP_IMAGE }}"
         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no opc@${{ vars.OCI_WEB1_PUB_IP }} \
           "rm -rf ~/.ssh/id_rsa"
